#!/bin/sh

# Remove old files
rm -r ./composeexample
# This instructs Compose to run django-admin.py startproject composeexample in a container, using the web service’s image and configuration.
docker-compose run web django-admin.py startapp composeexample .
# If you are running Docker on Linux, the files django-admin created are owned by root. This happens because the container runs as the root user. Change the ownership of the new files.
sudo chown -R $USER:$USER .
